
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team02-staff
owner: ucsb-cs156-f25
repo_name: team02-staff
pull_requests: [{"author":{"id":"U_kgDOBtP22A","is_bot":false,"login":"katelarrick","name":"Kate Larrick"},"headRefName":"Kate-Articles-Form","number":67,"title":"Added ArticleForm, ArticleForm stories, and ArticleForm tests","url":"https://github.com/ucsb-cs156-f25/team02-staff/pull/67"}]
